In [5]:
import numpy as np
a=np.array([[(1,2)],[(3,4)]])
print(a)

[[[1 2]]

 [[3 4]]]


In [6]:
a.transpose()

array([[[1, 3]],

       [[2, 4]]])

In [9]:
a

array([[[1, 2]],

       [[3, 4]]])

In [10]:
np.linalg.inv(a)

LinAlgError: Last 2 dimensions of the array must be square

In [13]:
u = np.eye(4)
u

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
import numpy as np
a=np.array([[(1,2)],[(3,4)]])
print(a)
np.linalg.inv(a)

[[[1 2]]

 [[3 4]]]


LinAlgError: Last 2 dimensions of the array must be square

In [30]:
j = np.array([[1,2], [3,4]])
j=j@j
j

array([[ 7, 10],
       [15, 22]])

In [31]:
y = np.array([[5.], [7.]])
np.linalg.solve(a, y)


LinAlgError: Last 2 dimensions of the array must be square

In [39]:
a = np.arange(0,10,2) 
b = np.arange(5)
m = np.dstack([a,b])
m

array([[[0, 0],
        [2, 1],
        [4, 2],
        [6, 3],
        [8, 4]]])

In [40]:
a = np.arange(0,10,2) 
b = np.arange(5)
m = np.vstack([a,b])
m

array([[0, 2, 4, 6, 8],
       [0, 1, 2, 3, 4]])

In [41]:
a = np.arange(0,10,2) 
b = np.arange(5)
m = np.hstack([a,b])
m

array([0, 2, 4, 6, 8, 0, 1, 2, 3, 4])

In [52]:
num = int(input())
for i in range(2,num):
    if num%2==0:
            print("number is not prime")
print("number is prime")

7
number is prime


In [53]:
def prime(a):
    for i in range(0,a):
        print(i)
a=int(input())
prime(a)


6
0
1
2
3
4
5


In [60]:
def prime(a):
    for i in range(2,a):
        if (a%i==0):
            print("not a prime")
            return
        else:
            print("prime")
            return
a=int(input())
prime(a)

78
not a prime


In [64]:
def prime(a):
    for i in range(2,a):
        if (i%2==0):
            print(i)
a=int(input())
prime(a)

80
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78


In [63]:
a=np.array([1,2,3,4,5,6,7,8,9])
for i in a:
    

AttributeError: 'numpy.ndarray' object has no attribute 'index'