In [26]:
import numpy as np
a=np.arange(12).reshape(3,2,2)
a

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [3]:
c = np.array( [ [1+8j,2], [3,4] ], dtype=complex )
c

array([[1.+8.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [4]:
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones( (2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [11]:
np.empty( (2,7) )   

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [12]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [17]:
np.linspace( 20, 10, 5) 

array([20. , 17.5, 15. , 12.5, 10. ])

In [18]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [24]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,np.pi,3)
b.dtype

dtype('float64')

In [35]:
import numpy as np
a=np.array([[[4,5,6],[7,8,9]],
            [[1,2,3],[7,2,6]],
            [[1,2,3],[7,2,6]]])
b=np.array([[[3,5,7],[8,8,8]],
            [[1,5,3],[2,5,8]],
            [[1,2,3],[7,2,6]]])
a=a@b
ptint(a)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [37]:
B = np.arange(3)
B

array([0, 1, 2])

In [38]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [43]:
a[:6:2]
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [42]:
a[:6:2]
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [56]:
a=np.arange(10)**2
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [57]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [59]:
a[:6]

array([ 0,  1,  4,  9, 16, 25], dtype=int32)

In [61]:
a[:6:2]

array([ 0,  4, 16], dtype=int32)

In [64]:
a[:6:2]=-10
a

array([-10,   1, -10,   9, -10,  25,  36,  49,  64,  81], dtype=int32)

In [70]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [71]:
b=np.array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [72]:
c = np.arange(24).reshape(2,3,4) 
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [75]:
c[1,1,3]

19